### ISSUE TITLE
Hello bro

### ISSUE THREAD

**Issue by userbox020** [buckyroberts/Python-Packet-Sniffer#5]
i excecuted the script, but in python 2 i got this error
Traceback (most recent call last):
  File "sniffer.py", line 3, in <module>
    from networking.ethernet import Ethernet
ImportError: No module named networking.ethernet

and in python 3 i got this error
Traceback (most recent call last):
  File "sniffer.py", line 93, in <module>
    main()
  File "sniffer.py", line 24, in main
    conn = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, s
AttributeError: module 'socket' has no attribute 'AF_PACKET'

could you give me a hand

**Comment by Izzy1647** [comment]
I've got the same problem too, still don't know what to do.

**Comment by Rachanainduri** [comment]
I executed the script, but in python 3 I got this error
Traceback (most recent call last):
File "sniffer.py", line 3, in
from networking.ethernet import Ethernet
ImportError: No module named networking.ethernet


can you help me in solving this error it's for my project

**Comment by Rachanainduri** [comment]
> i excecuted the script, but in python 2 i got this error
> Traceback (most recent call last):
> File "sniffer.py", line 3, in
> from networking.ethernet import Ethernet
> ImportError: No module named networking.ethernet
> 
> and in python 3 i got this error
> Traceback (most recent call last):
> File "sniffer.py", line 93, in
> main()
> File "sniffer.py", line 24, in main
> conn = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, s
> AttributeError: module 'socket' has no attribute 'AF_PACKET'
> 
> could you give me a hand
networking.ethernet is the file name that you probably didn't notice in the networking folder ,use the code in those and try it again it does work
